name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-southeast-2

      # Deploy to AWS CloudFormation
  #    - name: store to S3 AWS CloudFormation
  #      run: aws s3 cp ./
      - name: Deploy to AWS CloudFormation
        run: | 
              aws cloudformation deploy \
              --template-file test-track.yaml
              --stack-name abcd123 \
              --capabilities CAPABILITY_IAM CAPABILITY_IAM 
              
  #      with:
  #        name: cf-templates-1mebti1kt9a9q-ap-southeast-2
  #       template: 2025-05-10T074917.662Ztz5-aws-cf-s3-bucket-001.yaml
  #        no-fail-on-empty-changeset: "1"
  #        parameter-overrides: "BucketName=sdvdeploy-test001-bucket-with-cf"

         
